/*6*/
SHOW MASTER STATUS;
SHOW BINLOG EVENTS in 'binlog.000300' LIMIT 10;

'binlog.000300', '4', 'Format_desc', '1', '126', 'Server ver: 8.0.46-0ubuntu0.24.04.3, Binlog ver: 4'
'binlog.000300', '126', 'Previous_gtids', '1', '157', ''
'binlog.000300', '157', 'Anonymous_Gtid', '1', '236', 'SET @@SESSION.GTID_NEXT= \'ANONYMOUS\''
'binlog.000300', '236', 'Query', '1', '320', 'BEGIN'
'binlog.000300', '320', 'Table_map', '1', '393', 'table_id: 102 (classicmodels.payments)'
'binlog.000300', '393', 'Delete_rows', '1', '6411', 'table_id: 102 flags: STMT_END_F'
'binlog.000300', '6411', 'Xid', '1', '6442', 'COMMIT /* xid=392 */'
'binlog.000300', '6442', 'Anonymous_Gtid', '1', '6519', 'SET @@SESSION.GTID_NEXT= \'ANONYMOUS\''
'binlog.000300', '6519', 'Query', '1', '6666', 'use `classicmodels`; DROP TABLE IF EXISTS `ayp` /* generated by server */'
'binlog.000300', '6666', 'Anonymous_Gtid', '1', '6743', 'SET @@SESSION.GTID_NEXT= \'ANONYMOUS\''


/*7*/
USE mysql;
SELECT * FROM performance_schema.error_log
order by LOGGED desc
LIMIT 20;

'2026-08-06 09:22:55.504688', '16', 'Warning', 'MY-013360', 'Server', 'Plugin sha256_password reported: \'\'sha256_password\' is deprecated and will be removed in a future release. Please use caching_sha2_password instead\''
'2026-08-06 07:46:10.542639', '8', 'Warning', 'MY-013360', 'Server', 'Plugin mysql_native_password reported: \'\'mysql_native_password\' is deprecated and will be removed in a future release. Please use caching_sha2_password instead\''
'2026-08-06 07:45:53.546689', '0', 'System', 'MY-010931', 'Server', '/usr/sbin/mysqld: ready for connections. Version: \'8.0.46-0ubuntu0.24.04.3\'  socket: \'/var/run/mysqld/mysqld.sock\'  port: 3306  (Ubuntu).'
'2026-08-06 07:45:53.546630', '0', 'System', 'MY-011323', 'Server', 'X Plugin ready for connections. Bind-address: \'127.0.0.1\' port: 33060, socket: /var/run/mysqld/mysqlx.sock'
'2026-08-06 07:45:53.493245', '0', 'System', 'MY-013602', 'Server', 'Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.'
'2026-08-06 07:45:53.493222', '0', 'Warning', 'MY-010068', 'Server', 'CA certificate ca.pem is self signed.'
'2026-08-06 07:45:52.994250', '1', 'System', 'MY-013577', 'InnoDB', 'InnoDB initialization has ended.'
'2026-08-06 07:45:52.193397', '1', 'System', 'MY-013576', 'InnoDB', 'InnoDB initialization has started.'
'2026-08-06 07:45:52.149055', '0', 'System', 'MY-010116', 'Server', '/usr/sbin/mysqld (mysqld 8.0.46-0ubuntu0.24.04.3) starting as process 1860'
